USE [master]
GO
/****** Object:  Database [1gb_Gosreestr]    Script Date: 29-май-16 17:33:04 ******/
CREATE DATABASE [1gb_Gosreestr] ON  PRIMARY 
( NAME = N'Gosreestr', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\1gb_Gosreestr_Gosreestr_2012_10_27_12_07_05.mdf' , SIZE = 417472KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Gosreestr_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\1gb_Gosreestr_Gosreestr_log_2012_10_27_12_07_05.ldf' , SIZE = 2160960KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [1gb_Gosreestr] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [1gb_Gosreestr].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [1gb_Gosreestr] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [1gb_Gosreestr] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [1gb_Gosreestr] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [1gb_Gosreestr] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [1gb_Gosreestr] SET ARITHABORT OFF 
GO
ALTER DATABASE [1gb_Gosreestr] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [1gb_Gosreestr] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [1gb_Gosreestr] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [1gb_Gosreestr] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [1gb_Gosreestr] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [1gb_Gosreestr] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [1gb_Gosreestr] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [1gb_Gosreestr] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [1gb_Gosreestr] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [1gb_Gosreestr] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [1gb_Gosreestr] SET  DISABLE_BROKER 
GO
ALTER DATABASE [1gb_Gosreestr] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [1gb_Gosreestr] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [1gb_Gosreestr] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [1gb_Gosreestr] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [1gb_Gosreestr] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [1gb_Gosreestr] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [1gb_Gosreestr] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [1gb_Gosreestr] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [1gb_Gosreestr] SET  MULTI_USER 
GO
ALTER DATABASE [1gb_Gosreestr] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [1gb_Gosreestr] SET DB_CHAINING OFF 
GO
ALTER DATABASE [1gb_Gosreestr] SET  READ_WRITE 
GO
